-- schema.sql
-- MySQL schema and seed data for verdant_tech_db
-- Created: 2026-08-09

DROP DATABASE IF EXISTS verdant_tech_db;
CREATE DATABASE IF NOT EXISTS verdant_tech_db
  CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
USE verdant_tech_db;

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_id INT UNSIGNED NOT NULL,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  image_path VARCHAR(255),
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_products_category (category_id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Seed: categories
-- -----------------------------------------------------
INSERT INTO categories (category_name, slug) VALUES
  ('Indoor Vertical Towers', 'indoor-vertical-towers'),
  ('Smart IoT Controllers', 'smart-iot-controllers'),
  ('Organic Nutrient Formulas', 'organic-nutrient-formulas');

-- -----------------------------------------------------
-- Seed: products (6 sample hydroponic products)
-- Note: category_id values correspond to the three categories inserted above (1..3)
-- -----------------------------------------------------
INSERT INTO products (category_id, title, description, price, image_path, is_featured) VALUES
  (1, 'AeroGrow Tower 2000', 'Compact indoor vertical tower ideal for herbs and lettuce.', 499.99, 'uploads/tower1.jpg', 1),
  (1, 'LeafStack Pro', 'Modular vertical system with automated flood-and-drain cycles.', 749.00, 'uploads/tower2.jpg', 0),
  (2, 'VerdeConnect Hub', 'Wi-Fi enabled controller with mobile app and scheduling.', 129.99, 'uploads/controller1.jpg', 1),
  (2, 'HydroSense Plus', 'Sensor pack for pH, EC and temperature monitoring.', 199.50, 'uploads/controller2.jpg', 0),
  (3, 'BloomBoost Organic', 'Concentrated organic nutrient formula for leafy greens.', 29.99, 'uploads/nutrient1.jpg', 0),
  (3, 'RootRise Complete', 'Balanced nutrient mix for seedlings through harvest.', 39.99, 'uploads/nutrient2.jpg', 1);

-- -----------------------------------------------------
-- Seed: default admin user
-- Passwords should be hashed using PHP's password_hash() before inserting.
-- Example PHP (CLI) to generate a hash:
--   php -r "echo password_hash('YourChosenPassword', PASSWORD_DEFAULT).PHP_EOL;"
-- The following row uses a sample bcrypt hash generated by PHP's password_hash (replace with your own hash):
-- NOTE: Replace the sample hash below with the output from the PHP command above for a real password.
-- -----------------------------------------------------
INSERT INTO users (username, password_hash) VALUES
  ('admin', '$2y$10$usesomesillystringfore7hnbRJHxXVLeakoG8K30oukPsA.ztMG');

-- End of schema.sql
